name = "albert-biney-media"
main = "workers/media.ts"
compatibility_date = "2026-05-31"

routes = [
  { pattern = "albertbiney.com/media/*", zone_name = "albertbiney.com" }
]

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "albert-biney-media"
